# Generated by Django 2.2.7 on 2019-12-01 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guideprofilefeedback',
            name='user',
        ),
        migrations.DeleteModel(
            name='GuidePersonalTour',
        ),
        migrations.DeleteModel(
            name='GuideProfileFeedback',
        ),
    ]
