# Generated by Django 2.2.7 on 2019-12-05 08:26

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20191205_0824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='language',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True, null=True), blank=True, null=True, size=16),
        ),
    ]
